language: java
jdk:
- openjdk8

env:
  global:
  - secure: YAi7filzroFCYP7Zh/7mtospepo/3CzvnPs7KmFrA/pqo8eRHgAETOrK+jdRPu0y88+ft4D9l2wElHFOYac7C3TCjO+Th4IPsEDCqH1njjRfgxwAohSZmPOZp1rgzavTBlzf1gg/jefXdEv6HY4cNRXD0sIrZx5OgyGaY1vkYCYojP7qgKq3X7K8SaxRbVqcu+tLqPzMsUkL/wknIK7gXG0+mCheoh7KWJVStRQtpkm1fpdLgKfLMD8eIpF8ILE8ik8XWnfEaikh9oVEcoIK4EKktOhDXUNpXmWwx+Q/7+6xfDyG+XkgorR/HwRPj8miL96lQt6E66kZOJnhh0C5eHmyi8ttuOZ2noeyuqCJLJPSRyB/aJbFdkaqDEQvwkDD9RRpeGDNedr8EcgPtMAnbD++kYVo/hzqvOIOo1DxTtsGLAO2VfFzHOjOhaHFTnDXjrIbRJig7DVfdmkitjz7ZPRE0KvvkGWvtrUfC4cLn2GkPWeryH1eRj1vxgtIiwuoxWE/IgBlOhI14WI2dSnk2lS2jwQ9ttBeOhR5FpB1jsvLXlYRTcXHxYIrXHbTs/EhKvCpgG8B/xeOva3zI+SIkn+C65dwYAUTIqU4joLdK0oz7SkTTmpluAibr/hcw/QWBAJvSlPD1mTIr1sSof3cVgYOwwOT7m08YcS9VZIJVC0=

addons:
  sonarcloud:
    organization: swatarianess-stuff
    token:
      secure: YAi7filzroFCYP7Zh/7mtospepo/3CzvnPs7KmFrA/pqo8eRHgAETOrK+jdRPu0y88+ft4D9l2wElHFOYac7C3TCjO+Th4IPsEDCqH1njjRfgxwAohSZmPOZp1rgzavTBlzf1gg/jefXdEv6HY4cNRXD0sIrZx5OgyGaY1vkYCYojP7qgKq3X7K8SaxRbVqcu+tLqPzMsUkL/wknIK7gXG0+mCheoh7KWJVStRQtpkm1fpdLgKfLMD8eIpF8ILE8ik8XWnfEaikh9oVEcoIK4EKktOhDXUNpXmWwx+Q/7+6xfDyG+XkgorR/HwRPj8miL96lQt6E66kZOJnhh0C5eHmyi8ttuOZ2noeyuqCJLJPSRyB/aJbFdkaqDEQvwkDD9RRpeGDNedr8EcgPtMAnbD++kYVo/hzqvOIOo1DxTtsGLAO2VfFzHOjOhaHFTnDXjrIbRJig7DVfdmkitjz7ZPRE0KvvkGWvtrUfC4cLn2GkPWeryH1eRj1vxgtIiwuoxWE/IgBlOhI14WI2dSnk2lS2jwQ9ttBeOhR5FpB1jsvLXlYRTcXHxYIrXHbTs/EhKvCpgG8B/xeOva3zI+SIkn+C65dwYAUTIqU4joLdK0oz7SkTTmpluAibr/hcw/QWBAJvSlPD1mTIr1sSof3cVgYOwwOT7m08YcS9VZIJVC0=

script:
- "./gradlew sonarqube"

before_script:
- chmod +x gradlew

after_success:
- bash <(curl -s https://codecov.io/bash)

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
